### ISSUE TITLE
Validação da nota inserida

### ISSUE THREAD

**Issue by henriquevital00** [henriquevital00/Ticket-Machine#1]
A validação da nota inserida está incorreta, pois ela está sendo comparada ao vetor de notas apenas pelo indice 1.

Arquivo: TicketMachine.java

``` java
25    if (papelMoeda[1] == quantia)
```

![erro](https://user-images.githubusercontent.com/48650626/190834030-c04514d2-e1c7-47bc-8901-83ac8682a29b.PNG)

**Comment by GabrielBueno200** [comment]
PR #48: A verificação de inserção de notas foi corrigida substituindo a constante 1 pela variável "i" (cd31cfa)
