### ISSUE TITLE
A contagem de quantidade de notas de 5 reais do troco está sendo perdida

### ISSUE THREAD

**Issue by GabrielBueno200** [henriquevital00/Ticket-Machine#22]
A quantidade de notas de R$ 5 está sendo armazenada na posição 1 do array papeisMoedas, porém, logo após, esse mesmo índice é utilizado  para armazenar a quantidade de notas de R$ 2

```java
39    papeisMoeda[1] = new PapelMoeda(5, count);
```

```java
44    papeisMoeda[1] = new PapelMoeda(2, count);
```

**Comment by henriquevital00** [comment]
PR #52: Realizada correção de perda de valor de quantidade de notas de 5 reais devido a erro no índice do vetor (https://github.com/henriquevital00/Ticket-Machine/pull/52/commits/f094b28993566010489dd30c2450a336619e2276)
